# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Ahmedali3ff/Flyrank-internship-/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

My lane is Refresh / Content Opportunity Scoring.

I frame this as a ranking/scoring problem. The goal is to assign each content page a score that helps prioritize which pages should be reviewed first.

The output is not a guarantee that a page needs a refresh. Instead, it is a decision-support ranking that helps a content team focus limited review time on the pages with the strongest evidence of opportunity or risk.

In [17]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Target or proxy

For the starter project, I would use "is_declining_label" as a proxy target for pages that may deserve review.

The starter label is based on "trend_direction == "down"". This is useful for learning the ML workflow, but it is not a perfect future-looking target because it describes the current observation window.

For a stronger future version of the project, I would prefer a future-looking target such as whether a page experiences a meaningful decline during a future time window after the features have been measured.

In [18]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Success metric

My primary success metric will be Precision@K, especially Precision@50.

This matches the real decision because a content team has limited capacity and may only review the top 50 recommended pages. Precision@50 tells us how many of those top 50 recommendations match the chosen target or proxy.

I would also look at Average Precision and recall as supporting metrics, but Precision@50 is the clearest metric for the practical review-queue decision.

In [19]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

In [20]:
import pandas as pd

df = pd.read_csv("/content/flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

df[["content_id", "client_id", "impressions_90d", "sessions_90d", "trend_direction", "content_age_days"]].head(10)

Rows: 30000
Columns: 44

,content_id,client_id,impressions_90d,sessions_90d,trend_direction,content_age_days
0,content_304f48230142,client_f369cb89fc,3803,17,down,187
1,content_a1fb4e703a9e,client_4e07408562,15320,9,down,445
2,content_9aa793d4d895,client_7f2253d7e2,12581,11,down,141
3,content_331d6c4de07b,client_19581e27de,11751,78,stable,463
4,content_d99b7a2d90ca,client_3fdba35f04,19140,145,down,263
5,content_d4084a4bc775,client_f369cb89fc,3970,5,down,147
6,content_9a34b442b552,client_8722616204,20,1,down,90
7,content_a63219c6e95a,client_19581e27de,1724,28,stable,445
8,content_5e6c160719bc,client_6208ef0f77,32574,68,down,90
9,content_c27558df2b0c,client_19581e27de,1240,3,down,257

In [21]:
import os
import pandas as pd

matches = []

for root, dirs, files in os.walk("/content"):
    if "content_refresh_anonymized.csv" in files:
            matches.append(os.path.join(root, "content_refresh_anonymized.csv"))

            print("Found files:")
            for path in matches:
                print(path)

Found files:
/content/flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv

In [22]:
!git clone https://github.com/Ahmedali3ff/Flyrank-internship-.git /content/flyrank-ml-internship-starter

fatal: destination path '/content/flyrank-ml-internship-starter' already exists and is not an empty directory.

In [23]:
!rm -rf /content/flyrank-ml-internship-starter
!git clone https://github.com/Ahmedali3ff/Flyrank-internship-.git /content/flyrank-ml-internship-starter

Cloning into '/content/flyrank-ml-internship-starter'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 121 (delta 37), reused 104 (delta 32), pack-reused 0 (from 0)
Receiving objects: 100% (121/121), 1.82 MiB | 15.66 MiB/s, done.
Resolving deltas: 100% (37/37), done.

In [24]:
import pandas as pd

file_path = "/content/flyrank-ml-internship-starter/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(file_path)

print("Rows:", len(df))
print("Columns:", len(df.columns))

df[[
    "content_id",
        "client_id",
            "impressions_90d",
                "sessions_90d",
                    "trend_direction",
                        "content_age_days"
                        ]].head(10)

Rows: 30000
Columns: 44

,content_id,client_id,impressions_90d,sessions_90d,trend_direction,content_age_days
0,content_304f48230142,client_f369cb89fc,3803,17,down,187
1,content_a1fb4e703a9e,client_4e07408562,15320,9,down,445
2,content_9aa793d4d895,client_7f2253d7e2,12581,11,down,141
3,content_331d6c4de07b,client_19581e27de,11751,78,stable,463
4,content_d99b7a2d90ca,client_3fdba35f04,19140,145,down,263
5,content_d4084a4bc775,client_f369cb89fc,3970,5,down,147
6,content_9a34b442b552,client_8722616204,20,1,down,90
7,content_a63219c6e95a,client_19581e27de,1724,28,stable,445
8,content_5e6c160719bc,client_6208ef0f77,32574,68,down,90
9,content_c27558df2b0c,client_19581e27de,1240,3,down,257

## 5. Why ML beats a fixed rule here

A fixed rule can be useful as a transparent baseline, but it may treat every page using the same manually chosen thresholds and weights.

ML can combine multiple observable signals at the same time and learn patterns from the available examples. For example, impressions, sessions, position, CTR, content age, and engagement signals may interact in ways that are difficult to capture with one simple rule.

The purpose is not to use ML just because it is more complicated. ML is useful if it produces a better-ranked review queue on unseen data than a transparent baseline. If it does not improve the relevant validation metric, the fixed rule may be the better choice.

In [26]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.